refs #189, #190 and #97. Usable version of the unstable packages.
git-svn-id: file:///home/borja/svnDUMPS/ezwebplatform@1515 2a98c5bb-d66c-48ca-a96c-db028a6c31f4

diff --git a/debian_package/unstable/debian/ezweb-platform-apache2-common.prerm b/debian_package/unstable/debian/ezweb-platform-apache2-common.prerm
--- a/debian_package/unstable/debian/ezweb-platform-apache2-common.prerm
+++ b/debian_package/unstable/debian/ezweb-platform-apache2-common.prerm
@@ -1,13 +1,46 @@
 #!/bin/bash
 
-if [ "$1" == "remove" ]; then
-  INSTANCES=`/usr/sbin/update-ezweb-platform list enabled server apache2`
+###
+# Include debconf module
+#
+. /usr/share/debconf/confmodule
 
-  # Disable all Apache2 EzWeb instances
-  for conf_name in $INSTANCES; do
-    /usr/sbin/update-ezweb-platform disable $conf_name
-  done
+if [ -n "$DEBCONF_RECONFIGURE" ]; then
+  db_set ezweb-platform-common/abortupgrade false
+  exit 0
 fi
+
+case "${1}" in
+  failed-upgrade)
+    exit -1
+    ;;
+
+  upgrade)
+    db_get ezweb-platform-common/abortupgrade
+    if [ "$RET" == true ]; then
+      echo "Aborting EzWeb upgrade by user request"
+      exit 1
+    fi
+    ;;
+
+  remove)
+    INSTANCES=`/usr/sbin/update-ezweb-platform list enabled server apache2`
+
+    # Disable all Apache2 EzWeb instances
+    for conf_name in $INSTANCES; do
+      /usr/sbin/update-ezweb-platform disable $conf_name
+    done
+    ;;
+
+  abort-install|abort-upgrade|dissappear)
+    ;;
+
+  *)
+    echo "prerm called with unknown argument \"${1}\"" >&2
+    exit 1
+    ;;
+
+esac
 
 #DEBHELPER#
 
diff --git a/debian_package/unstable/debian/ezweb-platform-apache2-mod-python.prerm b/debian_package/unstable/debian/ezweb-platform-apache2-mod-python.prerm
--- a/debian_package/unstable/debian/ezweb-platform-apache2-mod-python.prerm
+++ b/debian_package/unstable/debian/ezweb-platform-apache2-mod-python.prerm
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+###
+# Include debconf module
+#
+. /usr/share/debconf/confmodule
+
+if [ -n "$DEBCONF_RECONFIGURE" ]; then
+  db_set ezweb-platform-common/abortupgrade false
+  exit 0
+fi
+
 reload_apache() {
   if apache2ctl configtest 2>/dev/null; then
     invoke-rc.d apache2 force-reload || true
@@ -9,21 +19,42 @@ reload_apache() {
   fi
 }
 
-if [ "$1" == "remove" ]; then
-  INSTANCES=`/usr/sbin/update-ezweb-platform list enabled server apache2 connection_type mod-python`
+case "${1}" in
+  failed-upgrade)
+    exit -1
+    ;;
 
-  # Disable all Apache2 EzWeb instances
-  for conf_name in $INSTANCES; do
-    RELOAD=1
-    /usr/sbin/update-ezweb-platform disable $conf_name
-  done
+  upgrade)
+    db_get ezweb-platform-common/abortupgrade
+    if [ "$RET" == true ]; then
+      echo "Aborting EzWeb upgrade by user request"
+      exit 1
+    fi
+    ;;
 
-  if [ "$RELOAD" == 1 ]; then
-    invoke-rc.d ezweb-platform-fastcgi start
-    reload_apache
-  fi
+  remove)
+    INSTANCES=`/usr/sbin/update-ezweb-platform list enabled server apache2 connection_type mod-python`
 
-fi
+    # Disable all Apache2 EzWeb instances
+    for conf_name in $INSTANCES; do
+      RELOAD=1
+      /usr/sbin/update-ezweb-platform disable $conf_name
+    done
+
+    if [ "$RELOAD" == 1 ]; then
+      reload_apache
+    fi
+    ;;
+
+  abort-install|abort-upgrade|dissappear)
+    ;;
+
+  *)
+    echo "prerm called with unknown argument \"${1}\"" >&2
+    exit 1
+    ;;
+
+esac
 
 #DEBHELPER#
 
diff --git a/debian_package/unstable/debian/ezweb-platform-common.prerm b/debian_package/unstable/debian/ezweb-platform-common.prerm
--- a/debian_package/unstable/debian/ezweb-platform-common.prerm
+++ b/debian_package/unstable/debian/ezweb-platform-common.prerm
@@ -1,19 +1,56 @@
 #!/bin/bash
 
-if [ "$1" == "remove" ]; then
-  # Disable all EzWeb instances
-  INSTANCES=`/usr/sbin/update-ezweb-platform list enabled`
+###
+# Include debconf module
+#
+. /usr/share/debconf/confmodule
 
-  for conf_name in $INSTANCES; do
-    /usr/sbin/update-ezweb-platform disable $conf_name
-  done
+if [ -n "$DEBCONF_RECONFIGURE" ]; then
+  db_set ezweb-platform-common/abortupgrade false
+  exit 0
 fi
+
+EZWEB_ADMIN_SCRIPT="/usr/sbin/update-ezweb-platform"
+
+case "${1}" in
+  failed-upgrade)
+    exit -1
+    ;;
+
+  upgrade)
+    db_get ezweb-platform-common/abortupgrade
+    if [ "$RET" == true ]; then
+      db_set ezweb-platform-common/configured false
+      echo "Aborting EzWeb upgrade by user request"
+      exit 1
+    fi
+    ;;
+
+  remove)
+    # Disable all EzWeb instances
+    INSTANCES=`$EZWEB_ADMIN_SCRIPT list enabled`
+
+    for conf_name in $INSTANCES; do
+      $EZWEB_ADMIN_SCRIPT disable $conf_name
+    done
+    ;;
+
+  abort-install|abort-upgrade|dissappear)
+    ;;
+
+  *)
+    echo "prerm called with unknown argument \"${1}\"" >&2
+    exit 1
+    ;;
+
+esac
+
 
 # Remove python object files
 find /usr/share/ezweb-platform -name "*.pyc" -delete
 
-# Remove
-rm -rf /var/lib/ezweb-platform
+# Remove .update-server and .update-db flag files
+rm -f /usr/share/ezweb-platform/.update-server /usr/share/ezweb-platform/.update-db
 
 #DEBHELPER#
 
diff --git a/debian_package/unstable/debian/ezweb-platform-fastcgi-common.prerm b/debian_package/unstable/debian/ezweb-platform-fastcgi-common.prerm
--- a/debian_package/unstable/debian/ezweb-platform-fastcgi-common.prerm
+++ b/debian_package/unstable/debian/ezweb-platform-fastcgi-common.prerm
@@ -1,18 +1,51 @@
 #!/bin/bash
 
-if [ "$1" == "remove" ]; then
-  # Disable all EzWeb instances
-  INSTANCES=`/usr/sbin/update-ezweb-platform list enabled connection_type fastcgi`
+###
+# Include debconf module
+#
+. /usr/share/debconf/confmodule
 
-  for conf_name in $INSTANCES; do
-    /usr/sbin/update-ezweb-platform disable $conf_name
-  done
-
-  PIDFILES=/var/run/ezweb-platform/*.pid
-  if [ ! -z "$PIDFILES" ]; then
-    invoke-rc.d ezweb-platform-fastcgi stop
-  fi
+if [ -n "$DEBCONF_RECONFIGURE" ]; then
+  db_set ezweb-platform-common/abortupgrade false
+  exit 0
 fi
+
+case "${1}" in
+  failed-upgrade)
+    exit -1
+    ;;
+
+  upgrade)
+    db_get ezweb-platform-common/abortupgrade
+    if [ "$RET" == true ]; then
+      echo "Aborting EzWeb upgrade by user request"
+      exit 1
+    fi
+    ;;
+
+  remove)
+    # Disable all EzWeb instances
+    INSTANCES=`/usr/sbin/update-ezweb-platform list enabled connection_type fastcgi`
+
+    for conf_name in $INSTANCES; do
+      /usr/sbin/update-ezweb-platform disable $conf_name
+    done
+
+    PIDFILES=/var/run/ezweb-platform/*.pid
+    if [ ! -z "$PIDFILES" ]; then
+      invoke-rc.d ezweb-platform-fastcgi stop
+    fi
+    ;;
+
+  abort-install|abort-upgrade|dissappear)
+    ;;
+
+  *)
+    echo "prerm called with unknown argument \"${1}\"" >&2
+    exit 1
+    ;;
+
+esac
 
 #DEBHELPER#
 
diff --git a/debian_package/unstable/debian/ezweb-platform-lighttpd-common.prerm b/debian_package/unstable/debian/ezweb-platform-lighttpd-common.prerm
--- a/debian_package/unstable/debian/ezweb-platform-lighttpd-common.prerm
+++ b/debian_package/unstable/debian/ezweb-platform-lighttpd-common.prerm
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+###
+# Include debconf module
+#
+. /usr/share/debconf/confmodule
+
+if [ -n "$DEBCONF_RECONFIGURE" ]; then
+  db_set ezweb-platform-common/abortupgrade false
+  exit 0
+fi
+
 reload_lighttpd() {
   if lighttpd -t 2>/dev/null; then
     invoke-rc.d lighttpd force-reload || true
@@ -8,17 +18,38 @@ reload_lighttpd() {
   fi
 }
 
-if [ "$1" == "remove" ]; then
-  INSTANCES=`/usr/sbin/update-ezweb-platform list enabled server lighttpd`
+case "${1}" in
+  failed-upgrade)
+    exit -1
+    ;;
 
-  # Disable all lighttpd EzWeb instances
-  for conf_name in $INSTANCES; do
-    RELOAD=1
-    /usr/sbin/update-ezweb-platform disable $conf_name
-  done
+  upgrade)
+    db_get ezweb-platform-common/abortupgrade
+    if [ "$RET" == true ]; then
+      echo "Aborting EzWeb upgrade by user request"
+      exit 1
+    fi
+    ;;
 
+  remove)
+    INSTANCES=`/usr/sbin/update-ezweb-platform list enabled server lighttpd`
 
-fi
+    # Disable all lighttpd EzWeb instances
+    for conf_name in $INSTANCES; do
+      RELOAD=1
+      /usr/sbin/update-ezweb-platform disable $conf_name
+    done
+    ;;
+
+  abort-install|abort-upgrade|dissappear)
+    ;;
+
+  *)
+    echo "prerm called with unknown argument \"${1}\"" >&2
+    exit 1
+    ;;
+
+esac
 
 #DEBHELPER#
 
diff --git a/debian_package/unstable/debian/ezweb-platform-lighttpd-fastcgi.prerm b/debian_package/unstable/debian/ezweb-platform-lighttpd-fastcgi.prerm
--- a/debian_package/unstable/debian/ezweb-platform-lighttpd-fastcgi.prerm
+++ b/debian_package/unstable/debian/ezweb-platform-lighttpd-fastcgi.prerm
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+###
+# Include debconf module
+#
+. /usr/share/debconf/confmodule
+
+if [ -n "$DEBCONF_RECONFIGURE" ]; then
+  db_set ezweb-platform-common/abortupgrade false
+  exit 0
+fi
+
 reload_lighttpd() {
   if lighttpd -t 2>/dev/null; then
     invoke-rc.d lighttpd force-reload || true
@@ -8,23 +18,45 @@ reload_lighttpd() {
   fi
 }
 
-if [ "$1" == "remove" ]; then
-  # Disable all the Lighttpd EzWeb instances
-  INSTANCES=`/usr/sbin/update-ezweb-platform list enabled server lighttpd connection_type fastcgi`
+case "${1}" in
+  failed-upgrade)
+    exit -1
+    ;;
 
-  invoke-rc.d ezweb-platform-fastcgi stop
+  upgrade)
+    db_get ezweb-platform-common/abortupgrade
+    if [ "$RET" == true ]; then
+      echo "Aborting EzWeb upgrade by user request"
+      exit 1
+    fi
+    ;;
 
-  for conf_name in $INSTANCES; do
-    RELOAD=1
-    /usr/sbin/update-ezweb-platform disable $conf_name
-  done
+  remove)
+    # Disable all the Lighttpd EzWeb instances
+    INSTANCES=`/usr/sbin/update-ezweb-platform list enabled server lighttpd connection_type fastcgi`
 
-  invoke-rc.d ezweb-platform-fastcgi start
-  if [ "$RELOAD" == 1 ]; then
-    reload_lighttpd
-  fi
+    invoke-rc.d ezweb-platform-fastcgi stop
 
-fi
+    for conf_name in $INSTANCES; do
+      RELOAD=1
+      /usr/sbin/update-ezweb-platform disable $conf_name
+    done
+
+    invoke-rc.d ezweb-platform-fastcgi start
+    if [ "$RELOAD" == 1 ]; then
+      reload_lighttpd
+    fi
+    ;;
+
+  abort-install|abort-upgrade|dissappear)
+    ;;
+
+  *)
+    echo "prerm called with unknown argument \"${1}\"" >&2
+    exit 1
+    ;;
+
+esac
 
 #DEBHELPER#
 
